#version of docker-compose syntax
version: '3'

#services to execute
services:
    web:
        stdin_open: true
        #build docker file (added dockerfile parameter as default for docker dompose is to look for a file named "Dockerfile" to build an image)
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
